<a href="https://colab.research.google.com/github/rkalshs/bigdataprac2603041/blob/main/03bdpractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
a = np.array([1,2,3], dtype=int)
a

array([1, 2, 3])

In [4]:
type(a)

numpy.ndarray

In [5]:
print(a.shape)
print(a.ndim)
print(a.dtype)

(3,)
1
int64


In [6]:
print(a.size)
print(a.itemsize)
print(a.nbytes)

3
8
24


## np.arage(시작, 끝 , 띄어쓰기)



In [7]:
import numpy as py

print(np.arange(3))
print(np.arange(3, 7))
print(np.arange(3, 7, 2))


[0 1 2]
[3 4 5 6]
[3 5]


## 배열 모양을 바꾸는 reshape()

In [11]:
import numpy as np

a = np.arange(12).reshape(3, 4) # < 2차원 배열
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
np.reshape(a, (2, 6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [15]:
import numpy as np
np.linspace(2, 3)


array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [17]:
(3-1) / (50-1)

0.04081632653061224

In [18]:
np.linspace(2, 3, 2)

array([2., 3.])

In [19]:
np.linspace(2, 3, 3)

array([2. , 2.5, 3. ])

In [26]:
np.linspace(2, 3, 3, retstep = True)


(array([2. , 2.5, 3. ]), np.float64(0.5))

In [27]:
a = np.linspace(2, 3, 3, retstep = True)
float(a[1])

0.5

In [28]:
np.linspace(2, 3, 3, retstep = True, endpoint = False)


(array([2.        , 2.33333333, 2.66666667]), np.float64(0.3333333333333333))

In [30]:
(3-2) / 3

0.3333333333333333

## Numpy 주요 함수

In [33]:
np.zeros((5,), dtype=int)

array([0, 0, 0, 0, 0])

In [34]:
np.zeros((5,), dtype = int)

array([0, 0, 0, 0, 0])

In [35]:
np.zeros((2,3 ), dtype = int )

array([[0, 0, 0],
       [0, 0, 0]])

In [36]:
np.zeros((2,3 ))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [37]:
np.ones((2,4 ))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [38]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [43]:
b = np.eye(3, 4 - 1)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
np.full([2,3] , 10)

array([[10, 10, 10],
       [10, 10, 10]])

In [46]:
np.full([2,3], (1,2,3))

array([[1, 2, 3],
       [1, 2, 3]])

In [48]:
np.full([4,3 ], fill_value=np.arange(4).reshape(4,1))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [49]:
np.arange(4).reshape(4,1)

array([[0],
       [1],
       [2],
       [3]])

In [54]:
import numpy as np
a = np.array([[10,20], [5,8], [1,2]])
a

array([[10, 20],
       [ 5,  8],
       [ 1,  2]])

In [55]:
a.sum()

np.int64(46)

In [56]:
a.sum(axis=0)

array([16, 30])

In [57]:
a.sum(axis=1)

array([30, 13,  3])

In [59]:
import numpy as np

print(np.sum(a))
print(np.sum(a, axis=0))
print(np.sum(a, axis=-1))

46
[16 30]
[30 13  3]


In [61]:
a = np.array([[3,5,8], [1,2,3]])
a

array([[3, 5, 8],
       [1, 2, 3]])

In [62]:
a.cumsum()

array([ 3,  8, 16, 17, 19, 22])

In [63]:
a.cumsum(axis=0)

array([[ 3,  5,  8],
       [ 4,  7, 11]])

In [64]:
a.cumsum(axis=1)

array([[ 3,  8, 16],
       [ 1,  3,  6]])

In [66]:
import numpy as np

a = np.power(np.arange(10), 2)
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [67]:
print(a[3])
print(a[-2])

9
64


In [68]:
print(a[1:4])
print(a[-5:-1])

[1 4 9]
[25 36 49 64]


In [69]:
print(a[8:2:-1])
print(a[-1:-7:-1])

[64 49 36 25 16  9]
[81 64 49 36 25 16]


In [70]:
a = np.arange(30).reshape(5, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [71]:
a[3]

array([18, 19, 20, 21, 22, 23])

In [72]:
a[-1]

array([24, 25, 26, 27, 28, 29])

In [73]:
a[-2, : ] # == a[-2]

array([18, 19, 20, 21, 22, 23])

In [74]:
a[-2, ]

array([18, 19, 20, 21, 22, 23])

In [75]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
print(x[1])
print(x[:5])

1
[0 1 2 3 4]


In [78]:
print(x[[2]])
print(x[[2, 3]])

[2]
[2 3]


In [79]:
x[[2, 3, 5, 8]]


array([2, 3, 5, 8])

In [80]:
x[np.array([5, 3, -4, 8])]

array([5, 3, 6, 8])

In [83]:
x[[0]]

array([0])

In [85]:
from numpy import arange

x = arange(56).reshape(7,8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [86]:
x[0]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [88]:
x[0, 1]

np.int64(1)

In [89]:
x[:, 2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [92]:
x[[1,3], [2,2 ]]

array([10, 26])

In [95]:
x[[0,2,4],:2]

array([[ 0,  1],
       [16, 17],
       [32, 33]])

In [96]:
a = np.arange(40).reshape(5, 8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [98]:
a[np.arange(2,4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [99]:
a[np.arange(2,4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [102]:
a[np.arange(2,4)][:, [1, 1]]

array([[17, 17],
       [25, 25]])

### 종료
