<a href="https://colab.research.google.com/github/rkalshs/bigdataprac2603041/blob/main/04w_arrary_stack_split.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 다차원 배열 결헙과 분리

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

np.concatenate((x,y), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
x = np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
y = np.arange(10,16).reshape(2,3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [ ]:
z = np.arange(20, 26).reshape(2, 3)
z

array([[20, 21, 22],
       [23, 24, 25]])

In [ ]:
import numpy as py

a = np.arange(1, 13).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
c = np.arange(1, 6, 2)
c

array([1, 3, 5])

In [ ]:
import numpy as py

np.hstack((a, np.expand_dims(c, axis=1)))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [ ]:
np.column_stack((a,c))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [ ]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.column_stack((a,b ))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
x = np.array([[1,2,3]])
y = np.array([[4,5,6]])
x

array([[1, 2, 3]])

In [ ]:
y

array([[4, 5, 6]])

In [ ]:
x.shape, y.shape

((1, 3), (1, 3))

In [ ]:
 np.column_stack((x,y))

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
np.c_[x,y]

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
np.c_[x,10,20,y]

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [ ]:
np.column_stack((x,10,20,y))

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [ ]:
import numpy as py
rg = np.random.default_rng(12345)
rg.random()


0.22733602246716966

In [ ]:
rg.random()

0.22733602246716966

In [ ]:
rg.random(5)

array([0.31675834, 0.79736546, 0.67625467, 0.39110955, 0.33281393])

In [ ]:
import numpy as py
rg = np.random.default_rng(1)
rg.integers(low=0, high=10, size=3)


array([4, 5, 7])

In [ ]:
import numpy as py
rg = np.random.default_rng(1)
rg.standard_normal(3)

array([0.34558419, 0.82161814, 0.33043708])

In [ ]:
rg.standard_normal(5)

array([ 0.59884621,  0.03972211, -0.29245675, -0.78190846, -0.25719224])

# 배열 결합 연습

In [ ]:
a = np.arange(1,4)
b = np.arange(4,7)
c = np.arange(7,10)
a, b, c


(array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]))

In [ ]:
p = np.arange(1, 7).reshape(2,3)
q = np.arange(11, 17).reshape(2,3)
r = np.arange(21, 27).reshape(2,3)
p, q, r

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[11, 12, 13],
        [14, 15, 16]]),
 array([[21, 22, 23],
        [24, 25, 26]]))

In [ ]:
np.vstack((a,b,c) )

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.vstack((p,q,r))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [ ]:
np.hstack((a,b,c))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.hstack((q,p,r))

array([[11, 12, 13,  1,  2,  3, 21, 22, 23],
       [14, 15, 16,  4,  5,  6, 24, 25, 26]])

In [ ]:
a,b,c

(array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]))

In [ ]:
np.column_stack((p,q,r))

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [ ]:
np.concatenate((p,q,r))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [ ]:
np.concatenate((p,q,r), axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [ ]:
np.concatenate((p,q,r), axis=1)




array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [ ]:
np.concatenate((p,q,r), axis=None)

array([ 1,  2,  3,  4,  5,  6, 11, 12, 13, 14, 15, 16, 21, 22, 23, 24, 25,
       26])

In [ ]:
np.c_[a,b,c]

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
np.column_stack((a,b,c))

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
np.column_stack([a,b,c])

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
np.vstack((p,q,r))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])